Service: ginsample
HttpPort: 9001

DataBase:
  DriverName: mysql
  DataSourceName: root:1234@tcp(127.0.0.1:3306)/testdb?charset=utf8&parseTime=true&loc=Asia%2FShanghai
  MaxOpenConn: 20
  MaxIdleConn: 10
  MaxConnLifeTime: 100

Log:
  Useable: true
  LogFilePath: ./logs
  LogFileName: ginsample.log